@url_dev=http://localhost:3052/v1/api/
####
POST {{url_dev}}/user/signup
Content-Type: application/json

{
    
        "name": "Trang",
        "username": "VTanhds",
        "email": "Vandhhfd@gmail.com",
        "password": "abc123"
    
}